\echo '=================== creating database ==================='

DROP DATABASE IF EXISTS job_monitoring;
CREATE DATABASE job_monitoring;
\c job_monitoring;

CREATE TYPE PIPELINE_EVENT_TYPE AS ENUM('start', 'finish', 'failed', 'outdated');

CREATE TABLE PIPELINE (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL
);

CREATE TABLE PIPELINE_EVENT (
    ID SERIAL PRIMARY KEY,
    PIPELINE_ID INT NOT NULL REFERENCES PIPELINE (ID),
    STATE PIPELINE_EVENT_TYPE NOT NULL,
    EVENT_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE DATASOURCE_EVENT_TYPE AS ENUM('read', 'write');


CREATE TABLE DATASOURCE_EVENT (
    ID SERIAL PRIMARY KEY,
    PIPELINE_ID INT NOT NULL REFERENCES PIPELINE (ID),
    EVENT_TYPE DATASOURCE_EVENT_TYPE NOT NULL,
    EVENT_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)


\echo '=================== loading debug data ==================='
